drabinajakubowa/coordinatepanel/urls.py
from django.conf.urls import url
from . import views
from .views import *
from django.contrib.auth.decorators import login_required

app_name = 'coordinatepanel'
urlpatterns = [
    url(r'^logowanie/$', views.coordinator_login, name='coordinator_login'),
    url(r'^wylogowanie/$', views.logout_view, name='logout'),
    url(r'^kalendarz/$', views.calendar, name='calendar'),
    url(r'^warsztaty-i-rekolekcje/$', views.music_trainings, name='music_trainings'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/$', views.training_details, name='training_details'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/raport.pdf/$', login_required(TrainingReportPDFView.as_view()),
        name='training_report'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/$', views.training_people, name='training_people'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<person_id>[0-9]+)/$', views.person_details,
        name='person_details'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<training_person_id>[0-9]+)/usun/$', views.delete_person,
        name='delete_person'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<training_person_id>[0-9]+)/edytuj/$',
        views.training_person_edit, name='training_person_edit'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<training_person_id>[0-9]+)/platnosci/$',
        views.person_payment, name='person_payment'),
    url(r'^statystyki/$', views.statistics, name='statistics'),
    url(r'^turnus/(?P<pk>[0-9]+)/$', views.batch_view, name='batch_view'),
    url(r'^turnus/(?P<pk>[0-9]+)/karta-obiegowa.pdf/$', login_required(CirculationCardPDFView.as_view()),
        name='circulation_card'),
    url(r'^turnus/(?P<pk>[0-9]+)/raport-pokoje.pdf/$', login_required(RoomsReportPDFView.as_view()),
        name='rooms_report'),
    url(r'^turnus/(?P<pk>[0-9]+)/pusty-raport-pokoje.pdf/$', login_required(RoomsEmptyReportPDFView.as_view()),
        name='empty_rooms_report'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/$', views.volunteers, name='volunteers_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/(?P<volunteer_id>[0-9]+)/wpisz/$', views.move_volunteer_to_base_list,
        name='move_volunteer_to_base_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/(?P<volunteer_id>[0-9]+)/rezerwowa/$',
        views.move_volunteer_to_reserve_list, name='move_volunteer_to_reserve_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/raport-wolontariusze.pdf/$',
        login_required(VolunteersReportPDFView.as_view()), name='volunteers_report'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/$', views.participants, name='participants_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/wpisz/$', views.move_participant_to_base_list,
        name='move_participant_to_base_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/rezerwowa/$',
        views.move_participant_to_reserve_list, name='move_participant_to_reserve_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<batch_participant_id>[0-9]+)/platnosci/$', views.participant_payment,
        name='participant_payment'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/raport-podopieczni.pdf/$',
        login_required(ParticipantsReportPDFView.as_view()), name='participants_report'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/$', views.participant_details,
        name='participant_details'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/zdjecie/$', views.participant_photo_edit,
        name='participant_photo_edit'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/(?P<volunteer_id>[0-9]+)/$', views.volunteer_details,
        name='volunteer_details'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/(?P<batch_volunteer_id>[0-9]+)/edytuj/$', views.batch_volunteer_edit,
        name='batch_volunteer_edit'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<batch_participant_id>[0-9]+)/edytuj/$', views.batch_participant_edit,
        name='batch_participant_edit'),
    url(r'^turnusy/$', views.batches, name='batches'),
    url(r'^turnus/(?P<batch_id>[0-9]+)/podopieczni/(?P<batch_participant_id>[0-9]+)/usun/$', views.delete_participant,
        name='delete_participant'),
    url(r'^turnus/(?P<batch_id>[0-9]+)/wolontariusze/(?P<batch_volunteer_id>[0-9]+)/usun/$', views.delete_volunteer,
        name='delete_volunteer'),
    url(r'^turnus/(?P<pk>[0-9]+)/(?P<id>[\w{}.-]{1,36})/zaswiadczenie.pdf/$',
        login_required(CertificatePDFView.as_view()), name='certificate'),
    url(r'^turnusy/wolontariusze/(?P<pk>[\w{}.-]{1,36})/umowa.pdf/$',
        login_required(VolunteerContractPDFView.as_view()), name='contract'),
    url(r'^turnusy/(?P<pk>[\w{}.-]{1,36})/umowa.pdf/$',
        login_required(ContractPDFView.as_view()), name='coordinator_contract'),
    url(r'^wydarzenia/$', views.events_view, name='events'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/$', views.event_details, name='event_details'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/informacje/$', views.event_info_edit, name='event_info_edit'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/$', views.event_volunteers, name='event_volunteers'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/(?P<event_volunteer_id>[0-9]+)/platnosci/$',
        views.event_volunteer_payment, name='event_volunteer_payment'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/$', views.event_participants, name='event_participants'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/(?P<event_participant_id>[0-9]+)/edycja/$',
        views.event_participant_edit, name='event_participant_edit'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/(?P<event_participant_id>[0-9]+)/platnosci/$',
        views.event_participant_payment, name='event_participant_payment'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/$', views.event_participant_details,
        name='event_participant_details'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/(?P<volunteer_id>[0-9]+)/$', views.event_volunteer_details,
        name='event_volunteer_details'),
    url(r'^wydarzenia/(?P<event_id>[0-9]+)/podopieczni/(?P<event_participant_id>[0-9]+)/usun/$',
        views.delete_event_participant, name='delete_event_participant'),
    url(r'^wydarzenia/(?P<event_id>[0-9]+)/wolontariusze/(?P<event_volunteer_id>[0-9]+)/usun/$',
        views.delete_event_volunteer, name='delete_event_volunteer'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/raport-wydarzenie.pdf/$', login_required(EventReportPDFView.as_view()),
        name='event_report'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/lista-wydarzenie.pdf/$', login_required(EventReportListPDFView.as_view()),
        name='event_report_list'),
    url(r'^pliki/$', views.get_files, name='get_files'),
    url(r'^statystyki/aktualizacja/$', views.update_participants_count, name='update_participants_count')
]

drabinajakubowa/dj/urls.py
from django.conf.urls import url
from . import views
from .views import *

app_name = 'dj'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^koszty/$', views.costs_view, name='costs'),
    url(r'^kalendarz/$', views.calendar, name='calendar'),
    url(r'^warsztaty/$', views.workshop_sign, name='workshop_sign'),
    url(r'^warsztaty/(?P<pk>[0-9]+)/$', views.workshop_details, name='workshop_details'),
    url(r'^warsztaty-muzyczne/$', views.music_training_sign, name='music_training_sign'),
    url(r'^warsztaty-muzyczne/(?P<pk>[0-9]+)/$', views.music_training_details, name='music_training_details'),
    url(r'^rekolekcje/$', views.retreat_sign, name='retreat_sign'),
    url(r'^rekolekcje/(?P<pk>[0-9]+)/$', views.retreat_details, name='retreat_details'),
    url(r'^turnusy/$', views.batches_view, name='batches'),
    url(r'^wydarzenia/$', views.UserEventFormView.as_view(), name='event_registration'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/$', views.event_details, name='event_details'),
    url(r'^turnusy/(?P<pk>[0-9]+)/$', views.batch_view, name='batch_view'),
    url(r'^turnusy/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/$', views.participant_details,
        name='participant_details'),
    url(r'^turnusy/(?P<pk>[0-9]+)/zadania$', views.batch_tasks_edit, name='batch_tasks_edit'),
    url(r'^dane/$', views.user_account_view, name='user_account'),
    url(r'^dane/zdjecie/$', views.photo_edit, name='photo_edit'),
    url(r'^dane/edytuj/$', views.user_account_edit, name='account_edit'),
    url(r'^dane/haslo/$', views.change_password, name='account_password'),
    url(r'^rejestracja/$', views.UserFormView.as_view(), name='registration'),
    url(r'^logowanie/$', views.login_view, name='login'),
    url(r'^wylogowanie/$', views.logout_view, name='logout'),
    url(r'^aktualnosci/$', views.news_view, name='news'),
    url(r'^turnusy/(?P<pk>[0-9]+)/(?P<id>[\w{}.-]{1,36})/zaswiadczenie.pdf$',
        login_required(CertificatePDFView.as_view()), name='certificate'),
    url(r'^turnusy/(?P<pk>[0-9]+)/(?P<id>[\w{}.-]{1,36})/zaswiadczenie-pielegniarz.pdf$',
        login_required(NurseCertificatePDFView.as_view()), name='nurse_certificate'),
    url(r'^turnusy/(?P<pk>[0-9]+)/(?P<id>[\w{}.-]{1,36})/zaswiadczenie-lekarz.pdf$',
        login_required(DoctorCertificatePDFView.as_view()), name='doctor_certificate'),
    url(r'^turnusy/(?P<pk>[0-9]+)/umowa.pdf$',
        login_required(ContractPDFView.as_view()), name='contract'),
    url(r'^turnusy/(?P<pk>[0-9]+)/umowa-pielegniarki.pdf$',
        login_required(NurseContractPDFView.as_view()), name='nurse_contract'),
    url(r'^turnusy/(?P<pk>[0-9]+)/umowa-lekarza.pdf$',
        login_required(DoctorContractPDFView.as_view()), name='doctor_contract'),
    url(r'^pliki/$', views.get_files, name='get_files'),
]

drabinajakubowa/drabinajakubowa/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dj.urls')),
    url(r'^koordynator/', include('coordinatepanel.urls')),
    url(r'^koordynator-domu/', include('homepanel.urls')),
    url(r'^captcha/', include('captcha.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'dj.views.bad_request'
handler403 = 'dj.views.permission_denied'
handler404 = 'dj.views.page_not_found'
handler500 = 'dj.views.server_error'

drabinajakubowa/homepanel/urls.py
from django.conf.urls import url
from . import views
from .views import *
from django.contrib.auth.decorators import login_required

app_name = 'homepanel'
urlpatterns = [
    url(r'^logowanie/$', views.home_coordinator_login, name='home_coordinator_login'),
    url(r'^wylogowanie/$', views.logout_view, name='logout'),
    url(r'^kalendarz/$', views.calendar, name='calendar'),
    url(r'^turnus/(?P<pk>[0-9]+)/$', views.batch_view, name='batch_view'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/$', views.volunteers, name='volunteers_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/$', views.participants, name='participants_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/wpisz/$',
        views.move_participant_to_base_list, name='move_participant_to_base_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/rezerwowa/$',
        views.move_participant_to_reserve_list, name='move_participant_to_reserve_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<id>[\w{}.-]{1,36})/zaswiadczenie.pdf/$',
        login_required(CertificatePDFView.as_view()), name='certificate'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<batch_participant_id>[0-9]+)/$', views.batch_participant_edit,
        name='batch_participant_edit'),
    url(r'^turnusy/$', views.batches, name='batches'),
    url(r'^wydarzenia/$', views.events, name='events'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/$', views.event_details, name='event_details'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/$', views.event_volunteers, name='event_volunteers'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/(?P<event_volunteer_id>[0-9]+)/platnosci/$',
        views.event_volunteer_payment, name='event_volunteer_payment'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/(?P<event_volunteer_id>[0-9]+)/usun/$',
        views.event_volunteer_delete, name='event_volunteer_delete'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/$', views.event_participants, name='event_participants'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/(?P<event_participant_id>[0-9]+)/platnosci/$',
        views.from_event_participant_payment, name='from_event_participant_payment'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/(?P<event_participant_id>[0-9]+)/usun/$',
        views.from_event_participant_delete, name='from_event_participant_delete'),
    url(r'^warsztaty-i-rekolekcje/$', views.retreats_and_trainings, name='retreats_and_trainings'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/$', views.training_details, name='training_details'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/$', views.training_people, name='training_people'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<person_id>[0-9]+)/$', views.person_details,
        name='person_details'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<training_person_id>[0-9]+)/platnosci/$',
        views.person_payment, name='person_payment'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<training_person_id>[0-9]+)/usun/$',
        views.retreat_person_delete, name='retreat_person_delete'),
    url(r'^pokoje/$', views.rooms, name='rooms'),
    url(r'^zaswiadczenia/$', views.certificates, name='certificates'),
    url(r'^podopieczni/$', views.all_participants, name='all_participants'),
    url(r'^podopieczni/dodaj/$', views.add_participant, name='add_participant'),
    url(r'^podopieczni/(?P<pk>[0-9]+)/$', views.participant_details, name='participant_details'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/turnusy/$', views.participant_sign, name='participant_sign'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/wydarzenia/$', views.event_participant_sign,
        name='event_participant_sign'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/wydarzenia/(?P<event_participant_id>[0-9]+)/usun/$',
        views.event_participant_delete, name='event_participant_delete'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/wydarzenia/(?P<event_participant_id>[0-9]+)/platnosci/$',
        views.event_participant_payment, name='event_participant_payment'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/turnusy/(?P<batch_id>[0-9]+)/platnosci/$', views.participant_payment,
        name='participant_payment'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/turnusy/(?P<batch_id>[0-9]+)/wpisz/$',
        views.move_participant_to_list, name='move_participant_to_list'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/turnusy/(?P<batch_id>[0-9]+)/usun/$', views.batch_participant_delete,
        name='batch_participant_delete'),
    url(r'^podopieczni/(?P<pk>[0-9]+)/edycja/$', views.edit_participant, name='edit_participant'),
    url(r'^podopieczni/usun/(?P<pk>[0-9]+)/$', views.delete_participant, name='delete_participant'),
    url(r'^rezerwacje/dodaj/$', views.add_booking, name='add_booking'),
    url(r'^rezerwacje/dodaj-1/(?P<pk>[0-9]+)/$', views.add_booking3, name='add_booking3'),
    url(r'^rezerwacje/dodaj-2/(?P<pk>[0-9]+)/$', views.add_booking_2, name='add_booking_2'),
    url(r'^rezerwacje/dodaj-z-posilkami/$', views.add_meals_booking, name='add_meals_booking'),
    url(r'^rezerwacje/(?P<pk>[0-9]+)/edycja-z-posilkami/$', views.edit_meals_booking, name='edit_meals_booking'),
    url(r'^rezerwacje/(?P<pk>[0-9]+)/edycja/$', views.edit_booking, name='edit_booking'),
    url(r'^rezerwacje/(?P<pk>[0-9]+)/edycja-2/$', views.edit_booking_2, name='edit_booking_2'),
    url(r'^rezerwacje/usun/(?P<pk>[0-9]+)/$', views.delete_booking, name='delete_booking'),
    url(r'^rezerwacje/usun/(?P<pk>[0-9]+)/$', views.delete_meals_booking, name='delete_meals_booking'),
    url(r'^rezerwacje-pokojow/$', views.all_bookings, name='all_bookings'),
    url(r'^pobyty-z-posilkami/$', views.all_bookings_meals, name='all_bookings_meals'),
    url(r'^rezerwacje/platnosci/(?P<booking_id>[0-9]+)/$', views.booking_payment, name='booking_payment'),
    url(r'^rezerwacje/(?P<pk>[0-9]+)/$', views.booking_details, name='booking_details'),
    url(r'^podopieczni/csv/$', views.get_participants_from_csv, name='get_participants_from_csv'),
    url(r'^podopieczni/aktualizacja/$', views.update_participants_count, name='update_participants_count')
]

drabinajakubowa/homepanel/models.py
from django.db import models

drabinajakubowa/homepanel/templates/homepanel/all_participants.html
{% extends "homepanel/base.html" %}

{% block content %}
    <section id="batch_participants" class="p-b-10">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <span class="float-right">
                        <a class="link-decoration-none"  href="{% url 'homepanel:get_participants_from_csv' %}">
                            <button class="btn btn-info m-b-10">Dane z csv</button>
                        </a>
                        <a class="link-decoration-none"  href="{% url 'homepanel:update_participants_count' %}">
                            <button class="btn btn-warning m-b-10">Aktualizuj</button>
                        </a>
                        <a class="link-decoration-none" href="{% url 'homepanel:add_participant' %}">
                            <button class="btn btn-default m-b-10">Dodaj podopiecznego</button>
                        </a>
                    </span>

                    <h2>Lista podopiecznych</h2>
                    <hr /><br />

                    <ul>
                        {% for participant in participants_list %}
                            <li class="lead">
                                <span class="col-sm-12 col-xs-12 col-md-12 row">
                                     <span class="col-xs-6 col-sm-6 col-md-6 col-lg-7">

                                         <a class="medium-bold" href="{% url 'homepanel:participant_details' participant.id %}">
                                             {{ participant.surname }} {{ participant.first_name }}
                                         </a>
                                     </span>
                                     <span class="col-xs-6 col-sm-6 col-md-6 col-lg-5 float-right text-right">
                                         <a class="link-decoration-none" href="{% url 'homepanel:participant_sign' participant.id %}">
                                            <button class="btn btn-primary btn-sm">Turnusy</button>
                                         </a>
                                         <a class="link-decoration-none" href="{% url 'homepanel:event_participant_sign' participant.id %}">
                                            <button class="btn btn-success btn-sm">Wydarzenia</button>
                                         </a>
                                         <a onclick="return confirm('Czy na pewno chcesz usunąć tego podopiecznego? Proces jest nieodwaracalny.')"
                                            class="link-decoration-none" href="{% url 'homepanel:delete_participant' participant.id %}">
                                             <button class="btn btn-danger btn-sm">Usuń</button>
                                         </a>
                                     </span>

                                </span>

                            </li>
                        {% endfor %}
                    </ul>

                    <br /><br />

                      <ul class="pagination offset-5">
                        {% if participants_list.has_previous %}
                          <li class="page-item"><a class="page-link" href="?page={{ participants_list.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                          <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                        {% endif %}
                        {% for i in participants_list.paginator.page_range %}
                          {% if participants_list.number == i %}
                            <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                          {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                          {% endif %}
                        {% endfor %}
                        {% if participants_list.has_next %}
                          <li class="page-item"><a class="page-link" href="?page={{ participants_list.next_page_number }}">&raquo;</a></li>
                        {% else %}
                          <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                        {% endif %}
                      </ul>

                    <br />
                </div>
            </div>
        </div>
    </section>

{% endblock %}

drabinajakubowa/homepanel/templates/homepanel/batch_participant_edit.html
{% extends "homepanel/base.html" %}
{% load mathfilters %}

{% block content %}
    <section id="registration">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">

                    <h2>{{ batch_participant.participant }} - przepisz na inny turnus</h2>
                    <hr /><br />

                    <form class="form-horizontal" action="" role="form" method="post">
                        {% csrf_token %}
                        {% include 'homepanel/includes/form_template.html' %}

                        <div class="form-group">
                            <div class="p-l-5 offset-lg-3 col-lg-9 offset-sm-5 col-sm-7">
                                <button type="submit" class="btn btn-primary">Zapisz</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>

{% endblock %}

drabinajakubowa/homepanel/templates/homepanel/participants.html
{% extends "homepanel/base.html" %}

{% block content %}
    <section id="batch_participants" class="p-b-10">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">

                    <h2>Lista podopiecznych</h2>
                    <hr /><br />

                    <ul>
                        {% for obj in batch_participants %}
                            <li class="lead">

                                <span class="col-sm-12 col-xs-12 col-md-12 row">
                                    <span class="col-xs-6 col-sm-6 col-md-7 col-lg-5">
                                        <a class="medium-bold" href="{%  url 'homepanel:participant_details' obj.participant.id %}">
                                              {{ obj.participant }}
                                        </a>
                                        {% if obj.room is not None %}, pokój: {{ obj.room }}{% endif %}
                                        {% if obj.volunteer is not None %}, wolontariusz: {{ obj.volunteer }}{% endif %}
                                    </span>
                                    <span class="col-xs-6 col-sm-6 col-md-5 col-lg-7 float-right text-right">
                                        {% if obj.batch.end_date >= now %}
                                            <a class="link-decoration-none" href="{%  url 'homepanel:move_participant_to_reserve_list' batch_id obj.participant.id %}">
                                                <button class="btn btn-info btn-sm">Rezerwa</button>
                                            </a>
                                            <a class="link-decoration-none" href="{%  url 'homepanel:batch_participant_edit' batch_id obj.participant.id %}">
                                                <button class="btn btn-warning btn-sm">Przepisz</button>
                                            </a>
                                        {% endif %}
                                        <a class="link-decoration-none" href="{% url 'homepanel:certificate' batch_id obj.unique_key %}">
                                            <button class="btn btn-success btn-sm">Zaświadczenie</button>
                                        </a>
                                     </span>
                                </span>

                            </li>
                        {% endfor %}
                    </ul>

                    <br />

                    <h2>Lista rezerwowa</h2>
                    <hr /><br />

                    <ul>
                        {% for obj in batch_participants_reserve %}
                            <li class="lead">

                                <span class="col-sm-12 col-xs-12 col-md-12 row">
                                    <span class="col-xs-6 col-sm-6 col-md-7 col-lg-5">
                                          <a class="medium-bold" href="{%  url 'homepanel:participant_details' obj.participant.id %}">
                                              {{ obj.participant }}
                                          </a>
                                        - {{ obj.sign_date|date:"d.m.Y H:i" }}
                                        {% if obj.room is not None %}, pokój: {{ obj.room }}{% endif %}
                                        {% if obj.volunteer is not None %}, wolontariusz: {{ obj.volunteer }}{% endif %}
                                    </span>
                                    <span class="col-xs-6 col-sm-6 col-md-5 col-lg-7 float-right text-right">
                                        {% if obj.batch.end_date >= now %}
                                            <a class="link-decoration-none" href="{%  url 'homepanel:move_participant_to_base_list' batch_id obj.participant.id %}">
                                                <button class="btn btn-info btn-sm">Lista</button>
                                            </a>
                                            <a class="link-decoration-none" href="{%  url 'homepanel:batch_participant_edit' batch_id obj.participant.id %}">
                                                <button class="btn btn-warning btn-sm">Przepisz</button>
                                            </a>
                                        {% endif %}
                                        <a class="link-decoration-none" href="{% url 'homepanel:certificate' batch_id obj.unique_key %}">
                                            <button class="btn btn-success btn-sm">Zaświadczenie</button>
                                        </a>
                                     </span>
                                </span>

                            </li>
                        {% endfor %}
                    </ul>

                    <br />

                    <a class="link-decoration-none"  href="{% url 'homepanel:batch_view' batch_id %}">
                        <button class="btn btn-default">Wróć</button>
                    </a>

                    <br /><br />
                </div>
            </div>
        </div>
    </section>

{% endblock %}