drabinajakubowa/coordinatepanel/urls.py
from django.conf.urls import url
from . import views
from .views import *
from django.contrib.auth.decorators import login_required

app_name = 'coordinatepanel'
urlpatterns = [
    url(r'^logowanie/$', views.coordinator_login, name='coordinator_login'),
    url(r'^wylogowanie/$', views.logout_view, name='logout'),
    url(r'^kalendarz/$', views.calendar, name='calendar'),
    url(r'^warsztaty-i-rekolekcje/$', views.music_trainings, name='music_trainings'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/$', views.training_details, name='training_details'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/raport.pdf/$', login_required(TrainingReportPDFView.as_view()),
        name='training_report'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/$', views.training_people, name='training_people'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<person_id>[0-9]+)/$', views.person_details,
        name='person_details'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<training_person_id>[0-9]+)/usun/$', views.delete_person,
        name='delete_person'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<training_person_id>[0-9]+)/edytuj/$',
        views.training_person_edit, name='training_person_edit'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<training_person_id>[0-9]+)/platnosci/$',
        views.person_payment, name='person_payment'),
    url(r'^statystyki/$', views.statistics, name='statistics'),
    url(r'^turnus/(?P<pk>[0-9]+)/$', views.batch_view, name='batch_view'),
    url(r'^turnus/(?P<pk>[0-9]+)/karta-obiegowa.pdf/$', login_required(CirculationCardPDFView.as_view()),
        name='circulation_card'),
    url(r'^turnus/(?P<pk>[0-9]+)/raport-pokoje.pdf/$', login_required(RoomsReportPDFView.as_view()),
        name='rooms_report'),
    url(r'^turnus/(?P<pk>[0-9]+)/pusty-raport-pokoje.pdf/$', login_required(RoomsEmptyReportPDFView.as_view()),
        name='empty_rooms_report'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/$', views.volunteers, name='volunteers_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/(?P<volunteer_id>[0-9]+)/wpisz/$', views.move_volunteer_to_base_list,
        name='move_volunteer_to_base_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/(?P<volunteer_id>[0-9]+)/rezerwowa/$',
        views.move_volunteer_to_reserve_list, name='move_volunteer_to_reserve_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/raport-wolontariusze.pdf/$',
        login_required(VolunteersReportPDFView.as_view()), name='volunteers_report'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/$', views.participants, name='participants_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/wpisz/$', views.move_participant_to_base_list,
        name='move_participant_to_base_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/rezerwowa/$',
        views.move_participant_to_reserve_list, name='move_participant_to_reserve_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<batch_participant_id>[0-9]+)/platnosci/$', views.participant_payment,
        name='participant_payment'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/raport-podopieczni.pdf/$',
        login_required(ParticipantsReportPDFView.as_view()), name='participants_report'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/$', views.participant_details,
        name='participant_details'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/zdjecie/$', views.participant_photo_edit,
        name='participant_photo_edit'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/(?P<volunteer_id>[0-9]+)/$', views.volunteer_details,
        name='volunteer_details'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/(?P<batch_volunteer_id>[0-9]+)/edytuj/$', views.batch_volunteer_edit,
        name='batch_volunteer_edit'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<batch_participant_id>[0-9]+)/edytuj/$', views.batch_participant_edit,
        name='batch_participant_edit'),
    url(r'^turnusy/$', views.batches, name='batches'),
    url(r'^turnus/(?P<batch_id>[0-9]+)/podopieczni/(?P<batch_participant_id>[0-9]+)/usun/$', views.delete_participant,
        name='delete_participant'),
    url(r'^turnus/(?P<batch_id>[0-9]+)/wolontariusze/(?P<batch_volunteer_id>[0-9]+)/usun/$', views.delete_volunteer,
        name='delete_volunteer'),
    url(r'^turnus/(?P<pk>[0-9]+)/(?P<id>[\w{}.-]{1,36})/zaswiadczenie.pdf/$',
        login_required(CertificatePDFView.as_view()), name='certificate'),
    url(r'^turnusy/wolontariusze/(?P<pk>[\w{}.-]{1,36})/umowa.pdf/$',
        login_required(VolunteerContractPDFView.as_view()), name='contract'),
    url(r'^turnusy/(?P<pk>[\w{}.-]{1,36})/umowa.pdf/$',
        login_required(ContractPDFView.as_view()), name='coordinator_contract'),
    url(r'^wydarzenia/$', views.events_view, name='events'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/$', views.event_details, name='event_details'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/informacje/$', views.event_info_edit, name='event_info_edit'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/$', views.event_volunteers, name='event_volunteers'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/(?P<event_volunteer_id>[0-9]+)/platnosci/$',
        views.event_volunteer_payment, name='event_volunteer_payment'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/$', views.event_participants, name='event_participants'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/(?P<event_participant_id>[0-9]+)/edycja/$',
        views.event_participant_edit, name='event_participant_edit'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/(?P<event_participant_id>[0-9]+)/platnosci/$',
        views.event_participant_payment, name='event_participant_payment'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/$', views.event_participant_details,
        name='event_participant_details'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/(?P<volunteer_id>[0-9]+)/$', views.event_volunteer_details,
        name='event_volunteer_details'),
    url(r'^wydarzenia/(?P<event_id>[0-9]+)/podopieczni/(?P<event_participant_id>[0-9]+)/usun/$',
        views.delete_event_participant, name='delete_event_participant'),
    url(r'^wydarzenia/(?P<event_id>[0-9]+)/wolontariusze/(?P<event_volunteer_id>[0-9]+)/usun/$',
        views.delete_event_volunteer, name='delete_event_volunteer'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/raport-wydarzenie.pdf/$', login_required(EventReportPDFView.as_view()),
        name='event_report'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/lista-wydarzenie.pdf/$', login_required(EventReportListPDFView.as_view()),
        name='event_report_list'),
    url(r'^pliki/$', views.get_files, name='get_files'),
    url(r'^statystyki/aktualizacja/$', views.update_participants_count, name='update_participants_count')
]

drabinajakubowa/dj/urls.py
from django.conf.urls import url
from . import views
from .views import *

app_name = 'dj'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^koszty/$', views.costs_view, name='costs'),
    url(r'^kalendarz/$', views.calendar, name='calendar'),
    url(r'^warsztaty/$', views.workshop_sign, name='workshop_sign'),
    url(r'^warsztaty/(?P<pk>[0-9]+)/$', views.workshop_details, name='workshop_details'),
    url(r'^warsztaty-muzyczne/$', views.music_training_sign, name='music_training_sign'),
    url(r'^warsztaty-muzyczne/(?P<pk>[0-9]+)/$', views.music_training_details, name='music_training_details'),
    url(r'^rekolekcje/$', views.retreat_sign, name='retreat_sign'),
    url(r'^rekolekcje/(?P<pk>[0-9]+)/$', views.retreat_details, name='retreat_details'),
    url(r'^turnusy/$', views.batches_view, name='batches'),
    url(r'^wydarzenia/$', views.UserEventFormView.as_view(), name='event_registration'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/$', views.event_details, name='event_details'),
    url(r'^turnusy/(?P<pk>[0-9]+)/$', views.batch_view, name='batch_view'),
    url(r'^turnusy/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/$', views.participant_details,
        name='participant_details'),
    url(r'^turnusy/(?P<pk>[0-9]+)/zadania$', views.batch_tasks_edit, name='batch_tasks_edit'),
    url(r'^dane/$', views.user_account_view, name='user_account'),
    url(r'^dane/zdjecie/$', views.photo_edit, name='photo_edit'),
    url(r'^dane/edytuj/$', views.user_account_edit, name='account_edit'),
    url(r'^dane/haslo/$', views.change_password, name='account_password'),
    url(r'^rejestracja/$', views.UserFormView.as_view(), name='registration'),
    url(r'^logowanie/$', views.login_view, name='login'),
    url(r'^wylogowanie/$', views.logout_view, name='logout'),
    url(r'^aktualnosci/$', views.news_view, name='news'),
    url(r'^turnusy/(?P<pk>[0-9]+)/(?P<id>[\w{}.-]{1,36})/zaswiadczenie.pdf$',
        login_required(CertificatePDFView.as_view()), name='certificate'),
    url(r'^turnusy/(?P<pk>[0-9]+)/(?P<id>[\w{}.-]{1,36})/zaswiadczenie-pielegniarz.pdf$',
        login_required(NurseCertificatePDFView.as_view()), name='nurse_certificate'),
    url(r'^turnusy/(?P<pk>[0-9]+)/(?P<id>[\w{}.-]{1,36})/zaswiadczenie-lekarz.pdf$',
        login_required(DoctorCertificatePDFView.as_view()), name='doctor_certificate'),
    url(r'^turnusy/(?P<pk>[0-9]+)/umowa.pdf$',
        login_required(ContractPDFView.as_view()), name='contract'),
    url(r'^turnusy/(?P<pk>[0-9]+)/umowa-pielegniarki.pdf$',
        login_required(NurseContractPDFView.as_view()), name='nurse_contract'),
    url(r'^turnusy/(?P<pk>[0-9]+)/umowa-lekarza.pdf$',
        login_required(DoctorContractPDFView.as_view()), name='doctor_contract'),
    url(r'^pliki/$', views.get_files, name='get_files'),
]

drabinajakubowa/drabinajakubowa/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dj.urls')),
    url(r'^koordynator/', include('coordinatepanel.urls')),
    url(r'^koordynator-domu/', include('homepanel.urls')),
    url(r'^captcha/', include('captcha.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'dj.views.bad_request'
handler403 = 'dj.views.permission_denied'
handler404 = 'dj.views.page_not_found'
handler500 = 'dj.views.server_error'

drabinajakubowa/homepanel/urls.py
from django.conf.urls import url
from . import views
from .views import *
from django.contrib.auth.decorators import login_required

app_name = 'homepanel'
urlpatterns = [
    url(r'^logowanie/$', views.home_coordinator_login, name='home_coordinator_login'),
    url(r'^wylogowanie/$', views.logout_view, name='logout'),
    url(r'^kalendarz/$', views.calendar, name='calendar'),
    url(r'^turnus/(?P<pk>[0-9]+)/$', views.batch_view, name='batch_view'),
    url(r'^turnus/(?P<pk>[0-9]+)/wolontariusze/$', views.volunteers, name='volunteers_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/$', views.participants, name='participants_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/wpisz/$',
        views.move_participant_to_base_list, name='move_participant_to_base_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<participant_id>[0-9]+)/rezerwowa/$',
        views.move_participant_to_reserve_list, name='move_participant_to_reserve_list'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<id>[\w{}.-]{1,36})/zaswiadczenie.pdf/$',
        login_required(CertificatePDFView.as_view()), name='certificate'),
    url(r'^turnus/(?P<pk>[0-9]+)/podopieczni/(?P<batch_participant_id>[0-9]+)/$', views.batch_participant_edit,
        name='batch_participant_edit'),
    url(r'^turnusy/$', views.batches, name='batches'),
    url(r'^wydarzenia/$', views.events, name='events'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/$', views.event_details, name='event_details'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/$', views.event_volunteers, name='event_volunteers'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/(?P<event_volunteer_id>[0-9]+)/platnosci/$',
        views.event_volunteer_payment, name='event_volunteer_payment'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/wolontariusze/(?P<event_volunteer_id>[0-9]+)/usun/$',
        views.event_volunteer_delete, name='event_volunteer_delete'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/$', views.event_participants, name='event_participants'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/(?P<event_participant_id>[0-9]+)/platnosci/$',
        views.from_event_participant_payment, name='from_event_participant_payment'),
    url(r'^wydarzenia/(?P<pk>[0-9]+)/podopieczni/(?P<event_participant_id>[0-9]+)/usun/$',
        views.from_event_participant_delete, name='from_event_participant_delete'),
    url(r'^warsztaty-i-rekolekcje/$', views.retreats_and_trainings, name='retreats_and_trainings'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/$', views.training_details, name='training_details'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/$', views.training_people, name='training_people'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<person_id>[0-9]+)/$', views.person_details,
        name='person_details'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<training_person_id>[0-9]+)/platnosci/$',
        views.person_payment, name='person_payment'),
    url(r'^warsztaty-i-rekolekcje/(?P<pk>[0-9]+)/uczestnicy/(?P<training_person_id>[0-9]+)/usun/$',
        views.retreat_person_delete, name='retreat_person_delete'),
    url(r'^pokoje/$', views.rooms, name='rooms'),
    url(r'^zaswiadczenia/$', views.certificates, name='certificates'),
    url(r'^podopieczni/$', views.all_participants, name='all_participants'),
    url(r'^podopieczni/dodaj/$', views.add_participant, name='add_participant'),
    url(r'^podopieczni/(?P<pk>[0-9]+)/$', views.participant_details, name='participant_details'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/turnusy/$', views.participant_sign, name='participant_sign'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/wydarzenia/$', views.event_participant_sign,
        name='event_participant_sign'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/wydarzenia/(?P<event_participant_id>[0-9]+)/usun/$',
        views.event_participant_delete, name='event_participant_delete'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/wydarzenia/(?P<event_participant_id>[0-9]+)/platnosci/$',
        views.event_participant_payment, name='event_participant_payment'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/turnusy/(?P<batch_id>[0-9]+)/platnosci/$', views.participant_payment,
        name='participant_payment'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/turnusy/(?P<batch_id>[0-9]+)/wpisz/$',
        views.move_participant_to_list, name='move_participant_to_list'),
    url(r'^podopieczni/(?P<participant_id>[0-9]+)/turnusy/(?P<batch_id>[0-9]+)/usun/$', views.batch_participant_delete,
        name='batch_participant_delete'),
    url(r'^podopieczni/(?P<pk>[0-9]+)/edycja/$', views.edit_participant, name='edit_participant'),
    url(r'^podopieczni/usun/(?P<pk>[0-9]+)/$', views.delete_participant, name='delete_participant'),
    url(r'^rezerwacje/dodaj/$', views.add_booking, name='add_booking'),
    url(r'^rezerwacje/dodaj-1/(?P<pk>[0-9]+)/$', views.add_booking3, name='add_booking3'),
    url(r'^rezerwacje/dodaj-2/(?P<pk>[0-9]+)/$', views.add_booking_2, name='add_booking_2'),
    url(r'^rezerwacje/dodaj-z-posilkami/$', views.add_meals_booking, name='add_meals_booking'),
    url(r'^rezerwacje/(?P<pk>[0-9]+)/edycja-z-posilkami/$', views.edit_meals_booking, name='edit_meals_booking'),
    url(r'^rezerwacje/(?P<pk>[0-9]+)/edycja/$', views.edit_booking, name='edit_booking'),
    url(r'^rezerwacje/(?P<pk>[0-9]+)/edycja-2/$', views.edit_booking_2, name='edit_booking_2'),
    url(r'^rezerwacje/usun/(?P<pk>[0-9]+)/$', views.delete_booking, name='delete_booking'),
    url(r'^rezerwacje/usun/(?P<pk>[0-9]+)/$', views.delete_meals_booking, name='delete_meals_booking'),
    url(r'^rezerwacje-pokojow/$', views.all_bookings, name='all_bookings'),
    url(r'^pobyty-z-posilkami/$', views.all_bookings_meals, name='all_bookings_meals'),
    url(r'^rezerwacje/platnosci/(?P<booking_id>[0-9]+)/$', views.booking_payment, name='booking_payment'),
    url(r'^rezerwacje/(?P<pk>[0-9]+)/$', views.booking_details, name='booking_details'),
    url(r'^podopieczni/csv/$', views.get_participants_from_csv, name='get_participants_from_csv'),
    url(r'^podopieczni/aktualizacja/$', views.update_participants_count, name='update_participants_count')
]

drabinajakubowa/homepanel/models.py
from django.db import models

drabinajakubowa/homepanel/templates/homepanel/includes/form_template.html
{% load widget_tweaks %}
{% for field in form %}
    <div class="form-group row">
        <label class="medium-bold col-form-label col-xs-12 col-sm-3 col-lg-3">{{ field.label_tag }}</label>
        <div class="col-xs-12 col-sm-7 col-lg-5">
            {{ field|attr:"class:form-control" }}
        </div>
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
{% endfor %}

drabinajakubowa/homepanel/templates/homepanel/includes/header.html
{% block content %}
    {% load staticfiles %}
    {% load auth_extras %}
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top home-coordinate-nav" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="{% url 'dj:index' %}"><img src="{% static 'images/logo3.png' %}"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse medium-bold" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    {% if request.get_full_path == "/" %}
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'news' %}">Aktualności</a>
                        </li>
                    {% endif %}
                    {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'homepanel:home_coordinator_login' %}">Logowanie</a>
                        </li>
                    {% endif %}
                    {% if request.user|has_group:"Koordynatorzy domu" or request.user|has_group:"Koordynatorzy zapisów" %}
                        <li class="nav-item">
                            <span class="nav-link js-scroll-trigger bold">Witaj, {{ request.user.username }}!</span>
                        </li>
                    {% endif %}
                    {% if request.user|has_group:"Koordynatorzy domu" %}
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'homepanel:all_bookings' %}">Rezerwacje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'homepanel:all_bookings_meals' %}">Posiłki</a>
                        </li>
                    {% endif %}
                    {% if request.user|has_group:"Koordynatorzy domu" or request.user|has_group:"Koordynatorzy zapisów" %}
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'homepanel:batches' %}">Turnusy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'homepanel:events' %}">Wydarzenia</a>
                        </li>
                        {% if request.user|has_group:"Koordynatorzy domu" %}
                            <li class="nav-item">
                                <a class="nav-link js-scroll-trigger" href="{% url 'homepanel:retreats_and_trainings' %}">Warsztaty/ rekolekcje</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link js-scroll-trigger" href="{% url 'homepanel:retreats_and_trainings' %}">Warsztaty/rekolekcje</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'homepanel:all_participants' %}">Podopieczni</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'homepanel:certificates' %}">Zaświadczenia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'homepanel:calendar' %}">Kalendarz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'homepanel:logout' %}">Wyloguj</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}